#!/usr/bin/env python3
"""
Derive the turnstile's runtime models from the three hand-edited source models.

Sources (edit these in Blockbench; each includes its arm(s)):
  models/block/turnstile.json             solo gate  (left + right halves)
  models/block/turnstile-wide-left.json   left half of a wide pair
  models/block/turnstile-wide-right.json  right half of a wide pair

Any element whose name contains "arm" is a swinging fare-arm and is pulled OUT of the
static body (TurnstileRenderer draws + rotates it, else it would double).

Outputs (regenerated, do not hand-edit):
  models/block/turnstile_body.json             solo posts+coins
  models/block/turnstile_wide_left_body.json   left-half posts+coins   (merged on right)
  models/block/turnstile_wide_right_body.json  right-half posts+coins  (merged on left)
  models/block/turnstile_arm_left.json         left fare-arm  (BER partial)
  models/block/turnstile_arm_right.json        right fare-arm (BER partial)
  blockstates/turnstile.json                   64 variants -> body by (facing, merge)
Run:  python3 tools/derive_turnstile_models.py
"""
import json, os

ROOT = "src/main/resources/assets/create_metro"
BLK = f"{ROOT}/models/block"

def load(name):
    with open(f"{BLK}/{name}.json") as f:
        return json.load(f)

def is_arm(e): return "arm" in e["name"]

def model_from(src, elements):
    m = {"__comment": "GENERATED by tools/derive_turnstile_models.py - do not edit",
         "textures": src.get("textures", {}), "elements": elements}
    if src.get("texture_size"): m["texture_size"] = src["texture_size"]
    return m

def write(name, src, elements):
    with open(f"{BLK}/{name}.json", "w") as fp:
        json.dump(model_from(src, elements), fp, indent=2)

solo  = load("turnstile")
wleft = load("turnstile-wide-left")
wright= load("turnstile-wide-right")

def body(src):  return [e for e in src.get("elements", []) if not is_arm(e)]
def arms(src, tag): return [e for e in src.get("elements", []) if is_arm(e) and e["name"].startswith(tag)]

# static bodies (arms removed)
write("turnstile_body",            solo,   body(solo))
write("turnstile_wide_left_body",  wleft,  body(wleft))
write("turnstile_wide_right_body", wright, body(wright))
# arm partials (from the solo model, which has both)
write("turnstile_arm_left",  solo, arms(solo, "left"))
write("turnstile_arm_right", solo, arms(solo, "right"))

# tidy stale files from earlier schemes
for stale in ("turnstile_body_ml", "turnstile_body_mr", "turnstile_body_mlr", "turnstile_arm"):
    p = f"{BLK}/{stale}.json"
    if os.path.exists(p): os.remove(p)

# blockstate: body chosen by merge; open/reversed handled by the renderer
YROT = {"north": 0, "east": 90, "south": 180, "west": 270}
def body_for(ml, mr):
    if mr and not ml: return "turnstile_wide_left_body"   # merged on right -> this is the LEFT block
    if ml and not mr: return "turnstile_wide_right_body"  # merged on left  -> this is the RIGHT block
    return "turnstile_body"                               # solo (or unreachable both)
variants = {}
for facing, y in YROT.items():
    for open_ in ("false", "true"):
        for ml in (False, True):
            for mr in (False, True):
                for rev in ("false", "true"):
                    key = (f"facing={facing},open={open_},merge_left={str(ml).lower()},"
                           f"merge_right={str(mr).lower()},reversed={rev}")
                    v = {"model": f"create_metro:block/{body_for(ml, mr)}"}
                    if y: v["y"] = y
                    variants[key] = v
with open(f"{ROOT}/blockstates/turnstile.json", "w") as fp:
    json.dump({"variants": variants}, fp, indent=2)

print("bodies+arms:", [n for n in sorted(os.listdir(BLK)) if n.startswith('turnstile_')])
print("arm elems  L:", [e['name'] for e in arms(solo,'left')], " R:", [e['name'] for e in arms(solo,'right')])
print("variants:", len(variants))
