#!/usr/bin/env python3
"""
Derive the turnstile's runtime models from the single hand-edited source model.

Source of truth: assets/create_metro/models/block/turnstile.json  (edit this in Blockbench).
Element naming convention: `left_*` / `right_*` for each half; any element whose name
contains "arm" is the swinging fare-arm (rendered/animated by TurnstileRenderer, so it is
kept OUT of the static block models).

Outputs (regenerated, do not hand-edit):
  models/block/turnstile_body[_ml|_mr|_mlr].json   static posts+coins, a side stripped per merge
  models/block/turnstile_arm_left.json             left fare-arm  (BER partial)
  models/block/turnstile_arm_right.json            right fare-arm (BER partial)
  blockstates/turnstile.json                       64 variants -> body model by (facing, merge)
Run:  python3 tools/derive_turnstile_models.py
"""
import json, os

ROOT = "src/main/resources/assets/create_metro"
SRC = f"{ROOT}/models/block/turnstile.json"

with open(SRC) as f:
    src = json.load(f)

textures = src.get("textures", {})
texture_size = src.get("texture_size")
elements = src.get("elements", [])

def is_arm(e):  return "arm" in e["name"]
def side(e):
    n = e["name"]
    return "left" if n.startswith("left_") else "right" if n.startswith("right_") else "shared"

body_elems  = [e for e in elements if not is_arm(e)]
shared      = [e for e in body_elems if side(e) == "shared"]
left_body   = [e for e in body_elems if side(e) == "left"]
right_body  = [e for e in body_elems if side(e) == "right"]
left_arm    = [e for e in elements if is_arm(e) and side(e) == "left"]
right_arm   = [e for e in elements if is_arm(e) and side(e) == "right"]

def model(els):
    m = {"__comment": "GENERATED by tools/derive_turnstile_models.py - do not edit",
         "textures": textures, "elements": els}
    if texture_size: m["texture_size"] = texture_size
    return m

def write(name, els):
    with open(f"{ROOT}/models/block/{name}.json", "w") as fp:
        json.dump(model(els), fp, indent=2)

# static bodies (arms excluded); a merged side hides that half's posts+coins
write("turnstile_body",     shared + left_body + right_body)
write("turnstile_body_ml",  shared + right_body)             # merged on left -> hide left half
write("turnstile_body_mr",  shared + left_body)              # merged on right -> hide right half
write("turnstile_body_mlr", shared)                          # (unreachable with pair-only grouping)
# arm partials (rendered + rotated by TurnstileRenderer)
write("turnstile_arm_left",  left_arm)
write("turnstile_arm_right", right_arm)

# remove stale generated files from the previous (single-arm, arrow) scheme
for stale in ("turnstile_ml", "turnstile_mr", "turnstile_mlr", "turnstile_arm",
              "turnstile_open_fwd", "turnstile_open_bwd"):
    p = f"{ROOT}/models/block/{stale}.json"
    if os.path.exists(p): os.remove(p)

# blockstate: static model chosen by merge combo (+ facing y); open/reversed handled by the BER
YROT = {"north": 0, "east": 90, "south": 180, "west": 270}
def body_for(ml, mr):
    if ml and mr: return "turnstile_body_mlr"
    if ml: return "turnstile_body_ml"
    if mr: return "turnstile_body_mr"
    return "turnstile_body"
variants = {}
for facing, y in YROT.items():
    for open_ in ("false", "true"):
        for ml in (False, True):
            for mr in (False, True):
                for rev in ("false", "true"):
                    key = (f"facing={facing},open={open_},merge_left={str(ml).lower()},"
                           f"merge_right={str(mr).lower()},reversed={rev}")
                    v = {"model": f"create_metro:block/{body_for(ml, mr)}"}
                    if y: v["y"] = y
                    variants[key] = v
with open(f"{ROOT}/blockstates/turnstile.json", "w") as fp:
    json.dump({"variants": variants}, fp, indent=2)

print("bodies:", [n for n in sorted(os.listdir(f'{ROOT}/models/block')) if n.startswith('turnstile')])
print("left_arm elems:", [e['name'] for e in left_arm], "right_arm elems:", [e['name'] for e in right_arm])
print("blockstate variants:", len(variants))
